### ISSUE TITLE
NS returned instead of availability 

### ISSUE THREAD

**Issue by rducic** [superflyer/ual#1]
When searching for flight that I know has availability for example:

No results found is returned for 06/11/15 UA801 LHR EWR IRX NS
Query: 06/11/15 UA801 LHR EWR IRX NS

However in results I see:
<strong>Available Cabins: </strong>F3, FN3, A3, ON2, O2, J9, JN9, C9, D9, Z9, ZN9, P9, PN9, R9, RN9, IN7, I7, Y9, YN9, B9, M9, E9, U9, H9, HN9, Q9, V9, W9, S9, T9, L9, K9, G0, N0, XN9, X9

**Comment by superflyer** [comment]
It works for me.  Make sure you've pulled the latest version and have lxml installed.  I had to switch it to lxml about a month ago because UA's html was so bad that the standard BeautifulSoup parser couldn't handle it.
